
name: Release tagged build

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release-tags:
    runs-on: ubuntu-24.04
    env:
      VERSION: ${{ github.ref_name }}
      RELEASE_VERSION: ${{ github.ref_name }}
      SNAPSHOT: ${{ endsWith(github.ref_name, '-snapshot') || contains(github.event.head_commit.message, '[snapshot]') }}
      PRERELEASE: ${{ endsWith(github.ref_name, '-pre') }}

    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 32
          submodules: recursive

      - name: Determine JDK versions
        id: list-jdk-versions
        shell: bash
        run: |
          (
            echo 'java-versions<<EOF'
            echo 8
            echo 17
            echo 21
            if [[ -f gradle/gradle-daemon-jvm.properties ]]; then
              yq -pprops -oprops '.toolchainVersion' gradle/gradle-daemon-jvm.properties
            fi
            echo EOF
          ) | tee -a "${GITHUB_OUTPUT}"

      - name: Set up JDK versions
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.list-jdk-versions.outputs.java-versions }}
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
          validate-wrappers: true

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup the workspace
        run: ./gradlew --build-cache --info --stacktrace -PmavenPublishUrl='${{ env.MAVEN_PUBLISHING_URL }}' ${{ inputs.workspace }}

      - name: Build the mod
        run: ./gradlew --build-cache --info --stacktrace -PmavenPublishUrl='${{ env.MAVEN_PUBLISHING_URL }}' assemble

      # Continue on error in the following steps to make sure releases still get made even if one of the methods fails

      - name: Delete old release if it already exists
        run: gh release delete --yes "${RELEASE_VERSION}"
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release under current tag
        run: |
          PRERELEASE_FLAG=""
          # DreamAssemblerXXL unfortunately breaks if prereleases are tagged as such on GitHub, so we only check for
          # $SNAPSHOT here.
          if [[ "$SNAPSHOT" == "true" ]]; then
            PRERELEASE_FLAG="--prerelease"
          fi
          CHANGELOG_OVERRIDE=".changelogs/${RELEASE_VERSION}.md"
          if [[ -f "$CHANGELOG_OVERRIDE" ]]; then
            echo "Using changelog override: $CHANGELOG_OVERRIDE"
            export "CHANGELOG_FILE=$CHANGELOG_OVERRIDE"
            echo "CHANGELOG_FILE=${CHANGELOG_FILE}" >> $GITHUB_ENV
          else
            echo "Generating changelog notes..."
            export "CHANGELOG_FILE=$(mktemp --suffix=.md)"
            echo "CHANGELOG_FILE=${CHANGELOG_FILE}" >> $GITHUB_ENV
            gh api --method POST -H "Accept: application/vnd.github+json" \
              "/repos/${GITHUB_REPOSITORY}/releases/generate-notes" \
              -f tag_name="${RELEASE_VERSION}" \
              --jq ".body" > "${CHANGELOG_FILE}"
          fi
          cat "${CHANGELOG_FILE}"
          gh release create "${RELEASE_VERSION}" -F "${CHANGELOG_FILE}" ${PRERELEASE_FLAG} ./build/libs/*.jar
        shell: bash
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Maven Repo
        uses: actions/checkout@v4
        with:
          repository: RecursivePineapple/mvn-repo

      - name: Publish to Maven
        run: ./gradlew --build-cache --info --stacktrace -Dmaven.repo.local=/home/runner/work/RecursivePineapple/mvn-repo assemble publishToMavenLocal -x test
        continue-on-error: true

      - name: Update Maven Repo
        uses: devops-infra/action-commit-push@v1.1.0
        working-directory: /home/runner/work/RecursivePineapple/mvn-repo
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Push ${{ github.ref_name }}"
