
name: Release tagged build

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  release-tags:
    uses: GTNewHorizons/GTNH-Actions-Workflows/.github/workflows/release-tags.yml@master
    secrets: inherit
    permissions:
      packages: write
      contents: read
    env:
      GITHUB_PACKAGE_TARGET: ${{ github.GITHUB_REPOSITORY }}
      MAVEN_USERNAME: ${{ github.actor }}
      MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
